{{- if .Values.dns.public.enabled }}
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: {{ include "es-dnsrelay.fullname" . }}-endpoints-public
  labels:
    {{- include "es-dnsrelay.labels" . | nindent 4 }}
  annotations:
    external-dns.alpha.kubernetes.io/public: "true"
spec:
{{- with .Values.dns.public.endpoints }} 
  endpoints: 
    {{- toYaml . | nindent 4 }} 
{{- end }} 
{{- end }}