apiVersion: v1
kind: Service
metadata:
  name: {{ include "es-tdarr-node.fullname" . }}
  labels:
    {{- include "es-tdarr-node.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: node
      protocol: TCP
      name: node
  selector:
    {{- include "es-tdarr-node.selectorLabels" . | nindent 4 }}
