apiVersion: v1
kind: Secret
metadata:
  name: {{ template "es-certstore.fullname" . }}-azure-principal
  labels:
    {{- include "es-certstore.labels" . | nindent 4 }}
type: Opaque
data:
  clientSecret:  {{ .Values.certificates.azure.servicePrincipal.clientSecret | b64enc | quote }}
  clientId: {{ .Values.certificates.azure.servicePrincipal.clientId | b64enc | quote }}
  tenantId: {{ .Values.certificates.azure.servicePrincipal.tenantId | b64enc | quote }}
  