{{- if .Values.fortios.enabled }}
{{- range .Values.fortios.devices }}
{{- $secret := . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "es-certstore.fullname" $ }}-fortios-{{ .name }}
  labels:
    {{- include "es-certstore.labels" $ | nindent 4 }}
type: Opaque
stringData:
{{ .data | toYaml | nindent 2 }}
---
{{- end }}
{{- end }}