{{- if .Values.storage.enabled }}
{{- range .Values.storage.persistentVolumes }}
{{- $persistentVolume := . -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $persistentVolume.name}}
{{- if $persistentVolume.namespace }}
  namespace: {{ $persistentVolume.namespace }}
{{- end }}
  labels:
    {{- include "es-storage.labels" $ | nindent 4 }}
{{- if $persistentVolume.labels }}
{{ toYaml $persistentVolume.labels | indent 4 }}
{{- end }}
  annotations:
{{- if $persistentVolume.annotations }}
{{ toYaml $persistentVolume.annotations | indent 4 }}
{{- end }}
spec:
{{ toYaml $persistentVolume.spec | indent 4 }}
---
{{- end }}
{{- end }}






  