{{- if .Values.storage.enabled }}
{{- range .Values.storage.smb.storageClasses }}
{{- $storageClass := . -}}

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ $storageClass.name}}
  labels:
    {{- include "es-storage.labels" $ | nindent 4 }}
  annotations:
{{ toYaml $storageClass.annotations | indent 4 }}
provisioner: smb.csi.k8s.io
parameters:
  source: {{ $storageClass.source | quote }}
  {{- if $storageClass.provisionerEnabled }}
  csi.storage.k8s.io/provisioner-secret-name: {{ include "es-storage.fullname" $ }}-storageclass-{{ $storageClass.name}}-smb-credentials
  csi.storage.k8s.io/provisioner-secret-namespace: {{ $.Release.Namespace }}
  {{- end }}
  csi.storage.k8s.io/node-stage-secret-name: {{ include "es-storage.fullname" $ }}-storageclass-{{ $storageClass.name}}-smb-credentials
  csi.storage.k8s.io/node-stage-secret-namespace: {{ $.Release.Namespace }}
volumeBindingMode: {{ $storageClass.volumeBindingMode}}
mountOptions:
{{- range $storageClass.mountOptions }}
  - {{ . | quote }}
{{- end }}
---


apiVersion: v1
kind: Secret
metadata:
  name: {{ include "es-storage.fullname" $ }}-storageclass-{{ $storageClass.name}}-smb-credentials
  labels:
    {{- include "es-storage.labels" $ | nindent 4 }}
type: Opaque
data:
  username:  {{ $storageClass.credentials.username | b64enc | quote }}
  password: {{ $storageClass.credentials.password | b64enc | quote }}
  {{- if $storageClass.credentials.domain }}
  domain: {{ $storageClass.credentials.domain | b64enc | quote }}
  {{- end }}
---
{{- end }}
{{- end }}






  