apiVersion: v1
kind: Service
metadata:
  name: {{ include "es-qbittorrent.fullname" . }}-tcp
  labels:
    {{- include "es-qbittorrent.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 6881
      targetPort: connections-tcp
      protocol: TCP
      name: connections-tcp
  selector:
    {{- include "es-qbittorrent.selectorLabels" . | nindent 4 }}
