apiVersion: v1
kind: Service
metadata:
  name: {{ include "es-qbittorrent.fullname" . }}-udp
  labels:
    {{- include "es-qbittorrent.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 6881
      targetPort: connections-udp
      protocol: UDP
      name: connections-udp
  selector:
    {{- include "es-qbittorrent.selectorLabels" . | nindent 4 }}
