{{- if and .Values.persistence.transcode.enabled (not .Values.persistence.transcode.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "es-plex.fullname" . }}-transcode
  labels:
    {{- include "es-plex.labels" . | nindent 4 }}
{{- if .Values.persistence.transcode.annotations }}
  annotations:
{{ toYaml .Values.persistence.transcode.annotations | indent 4 }}
{{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.transcode.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.transcode.size | quote }}
{{- if .Values.persistence.transcode.storageClass }}
{{- if (eq "-" .Values.persistence.transcode.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.transcode.storageClass }}"
{{- end }}
{{- end }}
{{- end -}}