apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "es-plex.fullname" . }}
  labels:
    {{- include "es-plex.labels" . | nindent 4 }}
spec:
  serviceName: {{ template "es-plex.fullname" . }}-headless
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  updateStrategy:
    type: {{ .Values.updateStrategyType }}
    {{- if (eq "OnDelete" .Values.updateStrategyType) }}
    rollingUpdate: null
    {{- end }}
  selector:
    matchLabels:
      {{- include "es-plex.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "es-plex.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "es-plex.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PLEX_CLAIM
              value: {{ .Values.config.claim | quote }}
            - name: TZ
              value: {{ .Values.config.timezone | quote }}
            - name: HOSTNAME
              value: {{ .Values.config.hostname | quote }}
            - name: ADVERTISE_IP
              value: {{ .Values.config.advertise | quote }}
            {{- range .Values.additionalEnv }}
            - name: {{ .name }}
              value: {{ tpl .value $ | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: 32400
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /config
            - name: transcode
              mountPath: /transcode
            - name: library
              mountPath: /mnt/library
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: config
      {{- if .Values.persistence.config.enabled }}
        persistentVolumeClaim:
          {{- if .Values.persistence.config.existingClaim }}
          claimName: {{ .Values.persistence.config.existingClaim }}
          {{- else }}
          claimName: {{ template "es-plex.fullname" . }}-config
          {{- end -}}
      {{- else }}
        emptyDir: {}
      {{- end }}
      - name: transcode
      {{- if .Values.persistence.transcode.enabled }}
        persistentVolumeClaim:
          {{- if .Values.persistence.transcode.existingClaim }}
          claimName: {{ .Values.persistence.transcode.existingClaim }}
          {{- else }}
          claimName: {{ template "es-plex.fullname" . }}-transcode
          {{- end -}}
      {{- else }}
        emptyDir: {}
      {{- end }}
      - name: library
      {{- if .Values.persistence.library.enabled }}
        persistentVolumeClaim:
          {{- if .Values.persistence.library.existingClaim }}
          claimName: {{ .Values.persistence.library.existingClaim }}
          {{- else }}
          claimName: {{ template "es-plex.fullname" . }}-library
          {{- end -}}
      {{- else }}
        emptyDir: {}
      {{- end }}