{{- if .Values.addressPools.enabled }}
{{- range .Values.addressPools.pools }}
{{- $pool := . -}}

apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ $pool.name}}
spec:
{{ $pool.spec | toYaml | indent 2 }}

---

{{- if $pool.advertiseL2 }}

apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: {{ $pool.name}}-advertise-l2
spec:
  ipAddressPools:
  - {{ $pool.name}}

---

{{- end }}

{{- end }}
{{- end }}