apiVersion: v2
name: es-dnsrelay
description: Helm chart for DNS management

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.0.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: 1.0.0


dependencies:
- name: external-dns
  version: 9.0.3
  repository: https://charts.bitnami.com/bitnami
  alias: public
  condition: public.enabled
- name: external-dns
  version: 9.0.3
  repository: https://charts.bitnami.com/bitnami
  alias: private-dns1
  condition: private-dns1.enabled
# - name: external-dns
#   version: 9.0.0
#   repository: https://charts.bitnami.com/bitnami
#   alias: private-dns2
#   condition: private-dns2.enabled
# - name: external-dns
#   version: 9.0.0
#   repository: https://charts.bitnami.com/bitnami
#   alias: private-dns3
#   condition: private-dns3.enabled
# - name: external-dns
#   version: 9.0.0
#   repository: https://charts.bitnami.com/bitnami
#   alias: private-dns4
#   condition: private-dns4.enabled
# - name: external-dns
#   version: 9.0.0
#   repository: https://charts.bitnami.com/bitnami
#   alias: private-dns5
#   condition: private-dns5.enabled
# - name: external-dns
#   version: 9.0.0
#   repository: https://charts.bitnami.com/bitnami
#   alias: private-dns6
#   condition: private-dns6.enabled