apiVersion: v1
kind: Service
metadata:
  name: {{ include "es-fileflows.fullname" . }}
  labels:
    {{- include "es-fileflows.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: server
      protocol: TCP
      name: http
    - port: 5001
      targetPort: http
      protocol: TCP
      name: server
  selector:
    {{- include "es-fileflows.selectorLabels" . | nindent 4 }}
